In [1]:
#first install the numpy pip install numpy
#import numpy
import numpy as np 
print(np.__version__)

1.20.3


In [14]:
# Row vector only contain one row
row_arr = np.array([1,2,3])
print("row vector",row_arr , sep="\n")
# column vector only contain one column
col_arr = np.array([[1],
                   [2],
                   [3]])
print("col vector",col_arr, sep="\n")
# Multidimenstional  array (tensor) have more then one col and row
mult_arr = np.array([[(1,2,3),
                     (4,5,6)],
                     [(5,6,7),
                     (8,9,0)]])
print("Multidimentional array",mult_arr, sep="\n")

row vector
[1 2 3]
col vector
[[1]
 [2]
 [3]]
Multidimentional array
[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 0]]]


In [31]:
# zeros value of specific shape and dtype 
arr = np.zeros((3,3), dtype="int")
print(arr)
# with any value
print("###################")
arr = np.full((5,5),7)
print(arr)
# value if specifice range
print("#############################3")
arr = np.arange(0,10,2)
print(arr)
# number of value in range
print("####################")
arr = np.linspace(0,8,9)
print(arr)
# genrate random values 
print("#############################")
arr = np.random.rand(2,3)
print(arr)
# random in integer 
print()
arr = np.random.randint(5,size=(2,3))
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
###################
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
#############################3
[0 2 4 6 8]
####################
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
#############################
[[0.14767428 0.91693859 0.23397463]
 [0.15969885 0.14149323 0.94380304]]

[[1 1 0]
 [2 3 4]]


In [37]:
# Array inspection (shape -> row,col, size -> total no.value, dtype -> type of array, astype -> typecast)
arr = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.astype(float))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
10
int32
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [42]:
# element wise adition, multiplication, scaler adition, scaler multiplication, min, max
arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])
print(arr+arr1)
print(arr*arr1)
print(arr+10)
print(arr*10)
print(arr.min())
print(arr.max())

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[11 12 13 14 15]
[10 20 30 40 50]
1
5


In [63]:
# indexing and slicing
# in 1-D
arr = np.array([1,2,3,4,5])
print(arr[3])
#slice
print(arr[1:3])
#reverse 
print(arr[::-1])
print("#################################3#")
# in 2-D
arr = np.array([(1,2,3,4),
                 (2,3,4,5)])
print(arr[1][3])
# also by this
print(arr[1,3])
#slice
print(arr[1,0:2])
print("######################################")
arr = np.array([[(1,2,3,4,5),
                (4,5,6,7,8)],
                
                [(11,22,33,44,55),
                 (66,77,88,99,10)]])
print(arr)
print("##############")
# arr[matrix][row][col]
print(arr[1][1][3])
#slice
print(arr[1,1,1:4])
# only corner point
print(arr[:,:,0::4])


4
[2 3]
[5 4 3 2 1]
#################################3#
5
5
[2 3]
######################################
[[[ 1  2  3  4  5]
  [ 4  5  6  7  8]]

 [[11 22 33 44 55]
  [66 77 88 99 10]]]
##############
99
[77 88 99]
[[[ 1  5]
  [ 4  8]]

 [[11 55]
  [66 10]]]


In [80]:
#reshape
arr1 = np.array([(1,2,3,4,5,6),(6,7,8,9,10,11)])
print(arr1)
print("##################33")
print(arr1.reshape(4,3))
print("#################################")
#flatten make row vector
print(arr1.ravel())
print("##########")
# concatenate
arr = np.array([(7,8,9,10,11,12),(2,3,3,4,5,6)])
print(np.concatenate((arr1,arr)))
print("###########################################################################333")
# transpose row into colume or vice versa
print(arr1.transpose())
print("###################")
#copy
arr2 = np.copy(arr1)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]
##################33
[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
#################################
[ 1  2  3  4  5  6  6  7  8  9 10 11]
##########
[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]
 [ 2  3  3  4  5  6]]
###########################################################################333
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]
 [ 6 11]]
###################
[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]


In [86]:
import cv2
# ceate gray scale image using numpy
image = np.zeros((500,500))
image[:,:] = 100
image = image[:,:] + 10
image[100:200,200:300] = 255
cv2.imwrite("smape.png",image)

True

In [88]:
image[100,200]

255.0